"""Emit golden fixtures for the Swift test suite from the validated oracle."""
import sys, os, json, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import engine as E
from oracle import (gregorian_to_jd, jd_to_iso_utc, jdn_for_date, SOLAR_TERMS,
                    delta_t_seconds)

E.load_vsop(sys.argv[1])
OUT = sys.argv[2]

def iso(y, mo, d, h=0, mi=0, s=0):
    return gregorian_to_jd(y, mo, d + (h * 3600 + mi * 60 + s) / 86400.0)

fx = {}
fx["_provenance"] = (
    "Generated by Tools/oracle/gen_fixtures.py from the reference oracle. "
    "The oracle's astronomy was validated against published equinox/solstice "
    "instants and equation-of-time landmarks; its Ba Zhai derivation was "
    "validated against the classical Kan row and the per-century life-gua "
    "rules; its year and day pillars were validated against published "
    "sexagenary years and the JDN day formula. See Documentation/"
    "TRADITIONAL_SYSTEMS.md.")

# --- solar terms -----------------------------------------------------------
fx["solarTerms"] = []
for y in (1950, 1984, 2000, 2025, 2026, 2050):
    for i, (name, cn, lon) in enumerate(SOLAR_TERMS):
        fx["solarTerms"].append({
            "year": y, "index": i, "name": name, "longitude": lon,
            "utc": jd_to_iso_utc(E.solar_term_jd_ut(y, i)),
        })

# --- delta T ---------------------------------------------------------------
# Stored at 9 decimals, like every other numeric fixture here. The precision
# a fixture is written at has to exceed the tolerance the test asserts with,
# or the rounding itself fails the test: these were stored at 4 decimals
# against a 1e-6 assertion, and every Delta-T case failed on the rounding
# rather than on any disagreement with the engine.
fx["deltaT"] = [{"year": y, "month": 6, "seconds": round(delta_t_seconds(y, 6), 9)}
                for y in (1900, 1925, 1950, 1975, 1990, 2000, 2010, 2026, 2049)]

# --- equation of time ------------------------------------------------------
fx["equationOfTime"] = [
    {"utc": jd_to_iso_utc(iso(2026, mo, d, 12)),
     "minutes": round(E.equation_of_time_minutes(iso(2026, mo, d, 12)), 4)}
    for mo, d in [(1, 15), (2, 11), (4, 15), (5, 14), (7, 26), (9, 1), (11, 3), (12, 25)]]

# --- sexagenary ------------------------------------------------------------
fx["yearPillars"] = []
for y in (1900, 1924, 1984, 1985, 2000, 2024, 2025, 2026, 2044):
    s, b = E.year_pillar_indices(y)
    fx["yearPillars"].append({"baziYear": y, "stem": s, "branch": b,
                              "name": E.STEMS[s] + E.BRANCHES[b]})

fx["dayPillars"] = []
for (y, mo, d) in [(1900, 1, 1), (1984, 2, 2), (2000, 1, 1), (2000, 1, 7),
                   (2024, 2, 29), (2025, 12, 31), (2026, 2, 17), (2050, 6, 15)]:
    j = jdn_for_date(y, mo, d)
    s, b = E.day_pillar_indices(j)
    fx["dayPillars"].append({"date": "%04d-%02d-%02d" % (y, mo, d), "jdn": j,
                             "stem": s, "branch": b,
                             "name": E.STEMS[s] + E.BRANCHES[b]})

# --- four pillars, including boundary cases --------------------------------
lichun26 = E.solar_term_jd_ut(2026, 0)
cases = [
    ("Seoul 1990-05-15 14:30 KST", iso(1990, 5, 15, 5, 30), 126.978),
    ("Seoul 1990-05-15 23:30 KST", iso(1990, 5, 15, 14, 30), 126.978),
    ("Seoul 1990-05-16 00:30 KST", iso(1990, 5, 15, 15, 30), 126.978),
    ("NYC 1984-02-02 12:00 EST", iso(1984, 2, 2, 17, 0), -74.006),
    ("Lichun 2026 minus 3min", lichun26 - 0.00208, 120.0),
    ("Lichun 2026 plus 3min", lichun26 + 0.00208, 120.0),
    ("Tokyo 2000-01-01 00:00 JST", iso(1999, 12, 31, 15, 0), 139.691),
]
fx["fourPillars"] = []
for label, jd, lon in cases:
    for policy in (E.LateZiPolicy.DAY_CHANGES_AT_23, E.LateZiPolicy.DAY_CHANGES_AT_MIDNIGHT):
        p = E.four_pillars(jd, lon, late_zi=policy)
        fx["fourPillars"].append({
            "label": label, "utc": jd_to_iso_utc(jd), "longitude": lon,
            "lateZiPolicy": policy,
            "year": list(p["year"]), "month": list(p["month"]),
            "day": list(p["day"]), "hour": list(p["hour"]),
            "solarHour": round(p["solarHour"], 6),
            "boundaryProximityMinutes": round(E.boundary_proximity_minutes(jd), 3),
            "name": "".join(E.STEMS[p[k][0]] + E.BRANCHES[p[k][1]]
                            for k in ("year", "month", "day", "hour")),
        })

# --- historical time zones -------------------------------------------------
# Generated from the system tz database via Python's zoneinfo, which is the
# same data Foundation reads. These are the cases that break a naive
# "interpret it in the device's zone" conversion.
from zoneinfo import ZoneInfo
import datetime as _dt

def _resolve(y, mo, d, h, mi, zone_id):
    """Mirror of CivilBirthTime.resolve(): enumerate self-consistent offsets."""
    zone = ZoneInfo(zone_id)
    naive = _dt.datetime(y, mo, d, h, mi, tzinfo=_dt.timezone.utc)
    offsets = set()
    for delta in (-86400, -3600, 0, 3600, 86400):
        probe = naive + _dt.timedelta(seconds=delta)
        offsets.add(int(probe.astimezone(zone).utcoffset().total_seconds()))
    consistent = []
    for off in offsets:
        cand = naive - _dt.timedelta(seconds=off)
        if int(cand.astimezone(zone).utcoffset().total_seconds()) == off:
            consistent.append(cand)
    consistent.sort()
    if len(consistent) == 1:
        return "unique", [consistent[0]]
    if len(consistent) >= 2:
        return "ambiguous", [consistent[0], consistent[-1]]
    skipped = max(naive - _dt.timedelta(seconds=o) for o in offsets)
    return "skipped", [skipped]

_tz_cases = [
    # Korea ran on UTC+8:30 from 1954 to 1961.
    (1955, 6, 15, 9, 0, "Asia/Seoul"),
    (1960, 1, 20, 4, 30, "Asia/Seoul"),
    # Either side of the 1961 return to UTC+9.
    (1961, 6, 1, 12, 0, "Asia/Seoul"),
    (1961, 9, 1, 12, 0, "Asia/Seoul"),
    # Korean summer time.
    (1987, 7, 1, 12, 0, "Asia/Seoul"),
    (1988, 7, 1, 12, 0, "Asia/Seoul"),
    # Spring forward 1987: 02:00 -> 03:00, so 02:30 never existed.
    (1987, 5, 10, 2, 30, "Asia/Seoul"),
    # Fall back 1987: 03:00 -> 02:00, so 02:30 happened twice.
    (1987, 10, 11, 2, 30, "Asia/Seoul"),
    # Ordinary modern readings.
    (1990, 5, 15, 14, 30, "Asia/Seoul"),
    (2026, 3, 15, 12, 0, "Asia/Seoul"),
    # Other zones, including US DST edges and a half-hour offset.
    (1984, 2, 2, 12, 0, "America/New_York"),
    (2023, 3, 12, 2, 30, "America/New_York"),
    (2023, 11, 5, 1, 30, "America/New_York"),
    (2000, 1, 1, 0, 0, "Asia/Tokyo"),
    (1975, 8, 20, 18, 45, "Europe/London"),
    (1995, 12, 25, 6, 15, "Asia/Kolkata"),
    (2010, 7, 4, 23, 59, "Australia/Sydney"),
]

fx["timeZones"] = []
for y, mo, d, h, mi, zone_id in _tz_cases:
    kind, instants = _resolve(y, mo, d, h, mi, zone_id)
    zone = ZoneInfo(zone_id)
    entry = {
        "year": y, "month": mo, "day": d, "hour": h, "minute": mi,
        "timeZone": zone_id, "kind": kind,
        "instant": instants[0].astimezone(_dt.timezone.utc)
                   .strftime("%Y-%m-%dT%H:%M:%SZ"),
        "offsetSeconds": int(instants[0].astimezone(zone).utcoffset().total_seconds()),
    }
    if kind == "ambiguous":
        entry["laterInstant"] = instants[1].astimezone(_dt.timezone.utc) \
            .strftime("%Y-%m-%dT%H:%M:%SZ")
    fx["timeZones"].append(entry)

# --- life gua and ba zhai --------------------------------------------------
fx["lifeGua"] = [{"baziYear": y, "polarity": pol, "gua": E.life_gua(y, pol)}
                 for y in range(1960, 2031) for pol in (E.Polarity.YANG, E.Polarity.YIN)]

fx["baZhai"] = []
for gua in (1, 2, 3, 4, 6, 7, 8, 9):
    sectors = E.bazhai_sectors(gua)
    fx["baZhai"].append({
        "gua": gua, "eastGroup": E.is_east_group(gua),
        "sectors": [{"degrees": d, "relation": sectors[d][0], "weight": sectors[d][2]}
                    for d in sorted(sectors)],
    })

# --- angular maths ---------------------------------------------------------
fx["angular"] = [
    {"a": a, "b": b,
     "signed": round(E.signed_angular_difference(a, b), 9),
     "distance": round(E.angular_distance(a, b), 9)}
    for a, b in [(0, 0), (0, 90), (90, 0), (0, 180), (0, 181), (180, 0),
                 (350, 10), (10, 350), (359.9, 0.1), (0.1, 359.9),
                 (-10, 10), (720, 90), (45.5, 315.25)]]

fx["directionalValue"] = []
for gua in (1, 7):
    for h in range(0, 360, 5):
        fx["directionalValue"].append(
            {"gua": gua, "heading": h, "value": round(E.directional_value(h, gua), 9)})

# --- end-to-end alignment sweep -------------------------------------------
natal = E.four_pillars(iso(1990, 5, 15, 5, 30), 126.978)
now = E.four_pillars(iso(2026, 3, 15, 3, 0), 126.978)
gua = E.life_gua(E.bazi_year_for(iso(1990, 5, 15, 5, 30)), E.Polarity.YANG)
fx["alignmentProfile"] = {
    "natalUTC": jd_to_iso_utc(iso(1990, 5, 15, 5, 30)),
    "nowUTC": jd_to_iso_utc(iso(2026, 3, 15, 3, 0)),
    "longitude": 126.978, "polarity": "yang", "gua": gua,
    "natalPillars": {k: list(natal[k]) for k in ("year", "month", "day", "hour")},
    "nowPillars": {k: list(now[k]) for k in ("year", "month", "day", "hour")},
    "dayMaster": E.day_master_element(natal),
    "dayMasterStrength": round(E.day_master_strength(natal), 9),
    "favourableElements": sorted(E.favourable_elements(natal)[0]),
    "natalBalance": round(E.natal_balance(natal), 9),
    "natalDistribution": {k: round(v, 9) for k, v in E.element_distribution(natal).items()},
}
fx["alignmentSweep"] = []
for h in range(0, 360, 5):
    a = E.alignment(natal, now, gua, h)
    fx["alignmentSweep"].append({
        "heading": h, "score": round(a["score"], 9), "level": a["level"],
        "spatial": round(a["spatial"], 9), "temporal": round(a["temporal"], 9),
        "personal": round(a["personal"], 9)})

with open(OUT, "w") as fh:
    json.dump(fx, fh, indent=1, ensure_ascii=False, sort_keys=False)
print("wrote", OUT)
for k, v in fx.items():
    if isinstance(v, list):
        print("  %-22s %d entries" % (k, len(v)))
